### PR TITLE
Endpoint

### PR DESCRIPTION
**Pull request by TusharShekhar1198**

### CODE REVIEW

**Comment by codingwithustushar** [comment]
@CodiumAI-Agent /review

**Comment by codingwithustushar** [comment]
@CodiumAI-Agent /review

**Comment by codingwithustushar** [comment]
@CodiumAI-Agent/review

**Comment by codingwithustushar** [comment]
@CodiumAI-Agent /review

**Comment by codingwithustushar** [comment]
@CodiumAI-Agent /review

**Comment by TusharShekhar1198** [comment]
@CodiumAI-Agent /review

**Comment by TusharShekhar1198** [comment]
@CodiumAI-Agent /review

**Comment by TusharShekhar1198** [comment]
@CodiumAI-Agent /review

**Comment by TusharShekhar1198** [comment]
@CodiumAI-Agent /review

**Pull request merged**
